name: Anisimoffs_actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python 
        python-version: [3.10.x]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
          
      - name: Run linter and pytest
        run: |
          make check

      - name: Publish code coverage stat
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_KEY }}
        with:
          coverageCommand: make test-coverage
          debug: true
